/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js';
import type { ContractOptions } from 'web3-eth-contract';
import type { EventLog } from 'web3-core';
import type { EventEmitter } from 'events';
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AddBought = ContractEventLog<{
  user: string;
  period: string;
  amount: string;
  timestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type ClaimBought = ContractEventLog<{
  user: string;
  period: string[];
  0: string;
  1: string[];
}>;
export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;

export interface CrowdsaleAbi extends BaseContract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): CrowdsaleAbi;
  clone(): CrowdsaleAbi;
  methods: {
    AGTI(): NonPayableTransactionObject<string>;

    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    PERIOD_CHANGER_ROLE(): NonPayableTransactionObject<string>;

    avaliableToBuy(): NonPayableTransactionObject<string>;

    bought(arg0: number | string | BN, arg1: string): NonPayableTransactionObject<string>;

    buy(tokenToPay: string, amountToGet: number | string | BN): PayableTransactionObject<void>;

    claim(period: (number | string | BN)[]): NonPayableTransactionObject<void>;

    currentVestingPeriod(): NonPayableTransactionObject<string>;

    getAmounts(period: (number | string | BN)[], user: string): NonPayableTransactionObject<string[]>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    getToken(token: string): NonPayableTransactionObject<void>;

    gift(
      account: string,
      amount: number | string | BN,
      timestamp: number | string | BN,
    ): NonPayableTransactionObject<void>;

    grantRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    hasRole(role: string | number[], account: string): NonPayableTransactionObject<boolean>;

    price(arg0: string): NonPayableTransactionObject<string>;

    renounceRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    revokeRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    setPrice(token: string, _price: number | string | BN): NonPayableTransactionObject<void>;

    startNewVestingPeriod(): NonPayableTransactionObject<void>;

    supportsInterface(interfaceId: string | number[]): NonPayableTransactionObject<boolean>;
  };
  events: {
    AddBought(cb?: Callback<AddBought>): EventEmitter;
    AddBought(options?: EventOptions, cb?: Callback<AddBought>): EventEmitter;

    ClaimBought(cb?: Callback<ClaimBought>): EventEmitter;
    ClaimBought(options?: EventOptions, cb?: Callback<ClaimBought>): EventEmitter;

    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(options?: EventOptions, cb?: Callback<RoleAdminChanged>): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(options?: EventOptions, cb?: Callback<RoleGranted>): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(options?: EventOptions, cb?: Callback<RoleRevoked>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: 'AddBought', cb: Callback<AddBought>): void;
  once(event: 'AddBought', options: EventOptions, cb: Callback<AddBought>): void;

  once(event: 'ClaimBought', cb: Callback<ClaimBought>): void;
  once(event: 'ClaimBought', options: EventOptions, cb: Callback<ClaimBought>): void;

  once(event: 'RoleAdminChanged', cb: Callback<RoleAdminChanged>): void;
  once(event: 'RoleAdminChanged', options: EventOptions, cb: Callback<RoleAdminChanged>): void;

  once(event: 'RoleGranted', cb: Callback<RoleGranted>): void;
  once(event: 'RoleGranted', options: EventOptions, cb: Callback<RoleGranted>): void;

  once(event: 'RoleRevoked', cb: Callback<RoleRevoked>): void;
  once(event: 'RoleRevoked', options: EventOptions, cb: Callback<RoleRevoked>): void;
}
