/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js';
import type { ContractOptions } from 'web3-eth-contract';
import type { EventLog } from 'web3-core';
import type { EventEmitter } from 'events';
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type RoleAdminChanged = ContractEventLog<{
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleGranted = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type RoleRevoked = ContractEventLog<{
  role: string;
  account: string;
  sender: string;
  0: string;
  1: string;
  2: string;
}>;
export type Trade = ContractEventLog<{
  orderID: string;
  fromTo: string[];
  nftAndToken: string[];
  idAndAmount: string[];
  additionalTokenReceivers: string[];
  allAmounts: string[];
  0: string;
  1: string[];
  2: string[];
  3: string[];
  4: string[];
  5: string[];
}>;

export interface ExchangeAbi extends BaseContract {
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): ExchangeAbi;
  clone(): ExchangeAbi;
  methods: {
    DEFAULT_ADMIN_ROLE(): NonPayableTransactionObject<string>;

    SIGNER_ROLE(): NonPayableTransactionObject<string>;

    forceTradeBatch(
      fromTo: string[][],
      nftAndToken: string[][],
      idAndAmount: (number | string | BN)[][],
      additionalTokenReceivers: string[][],
      allAmounts: (number | string | BN)[][],
    ): NonPayableTransactionObject<void>;

    getRoleAdmin(role: string | number[]): NonPayableTransactionObject<string>;

    grantRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    hasRole(role: string | number[], account: string): NonPayableTransactionObject<boolean>;

    orderIDUsed(arg0: number | string | BN): NonPayableTransactionObject<boolean>;

    renounceRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    revokeRole(role: string | number[], account: string): NonPayableTransactionObject<void>;

    supportsInterface(interfaceId: string | number[]): NonPayableTransactionObject<boolean>;

    trade(
      orderID: number | string | BN,
      fromTo: string[],
      nftAndToken: string[],
      idAndAmount: (number | string | BN)[],
      additionalTokenReceivers: string[],
      allAmounts: (number | string | BN)[],
      deadline: number | string | BN,
      signature: string | number[],
    ): PayableTransactionObject<void>;
  };
  events: {
    RoleAdminChanged(cb?: Callback<RoleAdminChanged>): EventEmitter;
    RoleAdminChanged(options?: EventOptions, cb?: Callback<RoleAdminChanged>): EventEmitter;

    RoleGranted(cb?: Callback<RoleGranted>): EventEmitter;
    RoleGranted(options?: EventOptions, cb?: Callback<RoleGranted>): EventEmitter;

    RoleRevoked(cb?: Callback<RoleRevoked>): EventEmitter;
    RoleRevoked(options?: EventOptions, cb?: Callback<RoleRevoked>): EventEmitter;

    Trade(cb?: Callback<Trade>): EventEmitter;
    Trade(options?: EventOptions, cb?: Callback<Trade>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: 'RoleAdminChanged', cb: Callback<RoleAdminChanged>): void;
  once(event: 'RoleAdminChanged', options: EventOptions, cb: Callback<RoleAdminChanged>): void;

  once(event: 'RoleGranted', cb: Callback<RoleGranted>): void;
  once(event: 'RoleGranted', options: EventOptions, cb: Callback<RoleGranted>): void;

  once(event: 'RoleRevoked', cb: Callback<RoleRevoked>): void;
  once(event: 'RoleRevoked', options: EventOptions, cb: Callback<RoleRevoked>): void;

  once(event: 'Trade', cb: Callback<Trade>): void;
  once(event: 'Trade', options: EventOptions, cb: Callback<Trade>): void;
}
